# default database to create in mysql for your app
database = "habitat"

# default remote admin credentials for mysql
mysql_user = "habitat"
mysql_pass = "habitat"

# my.cnf
max_connections   = "100"
connect_timeout   = "5"
wait_timeout    = "600"
max_allowed_packet  = "16M"
thread_cache_size       = "128"
sort_buffer_size  = "4M"
bulk_insert_buffer_size = "16M"
tmp_table_size    = "32M"
max_heap_table_size = "32M"

query_cache_limit   = "128K"
query_cache_size    = "64M"

log_warnings = "2"

default_storage_engine  = "InnoDB"
innodb_buffer_pool_size = "256M"
innodb_log_buffer_size  = "8M"
innodb_file_per_table = "1"
innodb_open_files = "400"
innodb_io_capacity  = "400"
innodb_flush_method = "O_DIRECT"

